# Generated by Django 5.0.2 on 2024-05-21 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_status', models.IntegerField(choices=[(1, 'download'), (3, 'error'), (2, 'history')], default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('delete_status', models.IntegerField(choices=[(1, ';live'), (0, 'delete')], default=1)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded', to='customers.customer')),
            ],
        ),
    ]
