# Generated by Django 5.0.2 on 2024-04-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaded_items',
            name='category',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloaded_items',
            name='game',
            field=models.CharField(default='Angry Birds', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloaded_items',
            name='img',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloaded_items',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='downloaded_items',
            name='rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
