# Generated by Django 5.0.2 on 2024-05-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
        ('games', '0002_games_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloaded_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('downloaded_dates', models.DateTimeField(auto_now_add=True)),
                ('games_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_history', to='games.games')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.history')),
            ],
        ),
    ]
