# Generated by Django 5.0.2 on 2024-05-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_downloaded_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
