# Generated by Django 5.0.2 on 2024-05-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_history_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaded_items',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_items', to='downloads.history'),
        ),
    ]
