# Generated by Django 5.0.2 on 2024-05-28 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0004_alter_downloaded_items_owner'),
        ('games', '0003_games_bg_img_games_sub_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloaded_items',
            name='games_id',
        ),
        migrations.AddField(
            model_name='history',
            name='games_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_history', to='games.games'),
        ),
    ]
