# Generated by Django 5.0.2 on 2024-05-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0007_remove_history_games_id_history_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='games',
            new_name='games_id',
        ),
    ]
