# Generated by Django 5.0.2 on 2024-08-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0003_travellers_alter_destination_details_place_descrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_details',
            name='des_img2',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='des_img3',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
