# Generated by Django 5.0.2 on 2024-08-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0004_destination_details_des_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_details',
            name='des_img4',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='des_img5',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
