# Generated by Django 5.0.2 on 2024-08-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0005_destination_details_des_img4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_details',
            name='place_descrip',
            field=models.TextField(max_length=500),
        ),
    ]
