# Generated by Django 5.0.2 on 2024-08-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0006_alter_destination_details_place_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_details',
            name='place_descrip',
            field=models.TextField(max_length=2000),
        ),
    ]
