# Generated by Django 5.0.2 on 2024-08-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0007_alter_destination_details_place_descrip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination_details',
            old_name='des_img3',
            new_name='img_visit1',
        ),
        migrations.RenameField(
            model_name='destination_details',
            old_name='des_img4',
            new_name='img_visit2',
        ),
        migrations.RenameField(
            model_name='destination_details',
            old_name='des_img5',
            new_name='img_visit3',
        ),
        migrations.AddField(
            model_name='destination_details',
            name='des_place_visit1',
            field=models.TextField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='des_place_visit2',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='des_place_visit3',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='des_place_visit4',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='des_place_visit5',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='des_place_visit6',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='img_visit4',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='img_visit5',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='img_visit6',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
