# Generated by Django 5.0.2 on 2024-08-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0008_rename_des_img3_destination_details_img_visit1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_details',
            name='name_visit1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='name_visit2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='name_visit3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='name_visit4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='name_visit5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='name_visit6',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
