# Generated by Django 5.0.2 on 2024-09-25 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0011_destinations_rename_place_register_yor_aplace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='id',
        ),
        migrations.AddField(
            model_name='destinations',
            name='destination_details_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='travelling.destination_details'),
            preserve_default=False,
        ),
    ]
