# Generated by Django 5.0.2 on 2024-11-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0013_destination_details_img1_destination_details_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_details',
            name='des1',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='des2',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='des3',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='des4',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='des5',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='name1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='name2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='name3',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='name4',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_details',
            name='name5',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
