# Generated by Django 5.0.2 on 2024-11-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0014_destination_details_des1_destination_details_des2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=100)),
                ('no_of_people', models.IntegerField()),
                ('email', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
                ('additional_phone', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
